### ISSUE TITLE
json mode for store method doesn't work

### ISSUE THREAD

**Issue by pbeninte** [philipp-mohr/dataclass-persistence#2]
as per title, I'd like to persist data inpure json instead of zip format.
At my newbie eyes, the code seems to allow this but the package installed with pip (0.2.1 version) does not recognize th mode keyword)
i don't find any documentation on this..
is it possible?
thanks

**Comment by philipp-mohr** [comment]
Please take a look at the following test: https://github.com/philipp-mohr/dataclass-persistence/blob/6c533995d3991bcab368006665758cb075f50914/tests/test_core.py#L66

On my test system it does work when using .store(file, mode='json').
Please provide a minimal code example if the current implementation fails your use case.

**Comment by pbeninte** [comment]
here a brief test:
from dataclasses import dataclass
from dataclass_persistence import Persistent,Mode

@dataclass
class tclass(Persistent):
    text1:str
    text2:str

t=tclass(
        text1='AA',
        text2='BB',)

file = "testpersistence"
print(t)
t.store(file,mode=Mode.JSON)

the following exception is generated

Exception has occurred: AttributeError
'str' object has no attribute 'with_name'
  File "C:\PythonCode\opzioni+Futures\testpersistence.py", line 24, in <module>
    t.store(file,mode=Mode.JSON)
AttributeError: 'str' object has no attribute 'with_name'
 
it works  if I use 
t.store(file,mode=Mode.ZIP)

it doesn't if I use

t.store(file,mode='json')

in ths case  I get the following error:
Exception has occurred: NotImplementedError
exception: no description
  File "C:\PythonCode\opzioni+Futures\testpersistence.py", line 15, in <module>
    t.store(file,mode='json')
NotImplementedError:

**Comment by philipp-mohr** [comment]
Should be fixed for version >0.3.0.

**Comment by philipp-mohr** [comment]
Should be fixed for version >0.3.0.
