### ISSUE TITLE
Can't load persisted dataclass with datetime

### ISSUE THREAD

**Issue by Maci3jPy** [philipp-mohr/dataclass-persistence#3]
Hi,

when i store the dataclass that has datetime values in it, the loading fails and return None, and throws following error:

`WARNING:root:Error occurred when creating instance of type <class 'datetime.datetime'> with string representation:'dict' object cannot be interpreted as an integer`

Here is the sample dataclass:

```
class Test:
    id: str
    start_date: datetime
    end_date: datetime
```

This is what returned after the invoking the load method

```
Test(id='E0:5A:1B:66:6C:18', start_date=None, end_date=None)
```

Date is inputed into the dataclass as `datetime.now()`

**Comment by philipp-mohr** [comment]
Fixed in version v0.3.3.
